# Generated by Django 3.2 on 2021-04-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0003_remove_backup_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backup')),
            ],
        ),
    ]
