# Generated by Django 3.2 on 2021-04-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_remove_backup_path'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_rows', to='backups.backup'),
        ),
    ]
