# Generated by Django 3.2 on 2021-04-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_backupparameter_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='path',
        ),
    ]
