# Generated by Django 3.2 on 2021-04-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backupfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupfile',
            name='name',
        ),
    ]
