# Generated by Django 3.2 on 2021-04-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_remove_backupfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupfile',
            name='relative_path',
            field=models.TextField(default='//'),
            preserve_default=False,
        ),
    ]
