# Generated by Django 3.2 on 2021-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_backupfile_relative_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(default='idle', max_length=128),
        ),
    ]
