# Generated by Django 3.2 on 2021-04-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0008_remove_backupfile_relative_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='status',
        ),
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('percentage', models.IntegerField()),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='backups.backup')),
            ],
        ),
    ]
