# Generated by Django 3.2 on 2021-04-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0010_backupstatus_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_items', to='backups.backup')),
            ],
        ),
    ]
