# Generated by Django 3.2 on 2021-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0011_backupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='directory',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
    ]
