# Generated by Django 3.2 on 2021-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0012_backupitem_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='filename',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
