# Generated by Django 3.2 on 2021-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0013_backupitem_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='file_size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
