# Generated by Django 3.2 on 2021-05-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0014_backupitem_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='scanner',
            field=models.CharField(default='local', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupitem',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
