# Generated by Django 3.2 on 2021-05-02 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0016_differentialinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='modified',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
