# Generated by Django 3.2 on 2021-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0018_alter_backupitem_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialinformation',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
