# Generated by Django 3.2 on 2021-05-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0020_backupitem_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='file_type',
            field=models.CharField(default='file', max_length=32),
            preserve_default=False,
        ),
    ]
