# Generated by Django 3.2 on 2021-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0022_auto_20210511_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupitem',
            name='savename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
