# Generated by Django 3.2 on 2021-05-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0023_backupitem_savename'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=1024)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='backups.backup')),
            ],
        ),
    ]
